Repository nodejs/node, pull requests merged in 2018-03, with the labels that each got.

#19081 v9.7.1 release proposal
  doc/changelogs/CHANGELOG_V9.md
  src/node_version.h
Labels: v9.x

#19164 build: update arm minimum supported platform
  BUILDING.md
Labels: build, doc, lts-watch-v4.x, lts-watch-v6.x, lts-watch-v8.x

#19236 n-api,test: add a new.target test to addons-napi
  test/addons-napi/test_new_target/binding.c
  test/addons-napi/test_new_target/binding.gyp
  test/addons-napi/test_new_target/test.js
Labels: dont-land-on-v4.x, dont-land-on-v6.x, n-api, test

#19292 assert: improve assert()/assert.ok() performance
  benchmark/assert/ok.js
  lib/assert.js
Labels: assert, performance

#19415 net: emit error on invalid address family
  doc/api/errors.md
  lib/internal/errors.js
  lib/net.js
  test/parallel/test-net-options-lookup.js
Labels: errors, net

#19610 doc: add BethGriggs to collaborators
  README.md
Labels: author ready, doc, fast-track

#19681 2018-03-29, Version 4.9.1 'Argon' (Maintenance)
  CHANGELOG.md
  src/node_version.h
Labels: meta, v4.x

#19679 2018-03-29, Version 8.11.1 'Carbon' (LTS)
  CHANGELOG.md
  doc/changelogs/CHANGELOG_V8.md
  src/node_version.h
Labels: meta, v8.x

#19678 2018-03-29, Version 9.10.1 (Current)
  CHANGELOG.md
  doc/changelogs/CHANGELOG_V9.md
  src/node_version.h
Labels: meta, v9.x
